---
- name: Install prometheus-node-exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Enable node exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    enabled: true
    state: started