---
all:
  children:
    game_servers:
      hosts:
        zone01:
          ansible_host: 10.10.1.11

        zone02:
          ansible_host: 10.10.1.12

        zone03:
          ansible_host: 10.10.1.13

        zone04:
          ansible_host: 10.10.1.14

        zone05:
          ansible_host: 10.10.1.15